#!/bin/sh

# references:
# http://techblog.appnexus.com/2011/managing-ssh-sockets-in-gnu-screen/
# https://gist.github.com/martijnvermaat/8070533
# http://stackoverflow.com/questions/21378569/how-to-auto-update-ssh-agent-environment-variables-when-attaching-to-existing-tm
# https://unix.stackexchange.com/questions/657250/how-to-distinguish-ssh-from-scp-in-ssh-rc

if [ -n "$SSH_TTY" ] && [ -n "$SSH_AUTH_SOCK" ]; then
    ln -sf "$SSH_AUTH_SOCK" "$HOME/.ssh/ssh_auth_sock.$(hostname)"
fi

# Don't break x11 Forwarding:
# Taken from the sshd(8) manpage.
if read proto cookie && [ -n "$DISPLAY" ]; then
    if [ $(echo $DISPLAY | cut -c1-10) = 'localhost:' ]; then
        # X11UseLocalhost=yes
        echo add unix:$(echo $DISPLAY |
            cut -c11-) $proto $cookie
    else
        # X11UseLocalhost=no
        echo add $DISPLAY $proto $cookie
    fi | xauth -q -
fi
