############################
## General
############################

# passthrough color escape sequences for base16
set -g allow-passthrough on

# enable support for CSI u in tmux (requires terminal support)
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# increase repeat time for repeatable commands
set -g repeat-time 1000

# refresh 'status-left' and 'status-right' more often
set -g status-interval 5

# increase imabe buffer size so that larger images actually preview properly
set -s input-buffer-size 20000000

set-option -g update-environment "TERM \
                                  TERM_PROGRAM \
                                  SSH_AUTH_SOCK \
                                  SSH_CONNECTION \
                                  DISPLAY"

############################
## Binds
############################

# Allow us to reload our Tmux configuration while using Tmux
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# remap prefix from 'C-b' to 'C-a'
unbind C-b
if-shell -b '[ -z "$SSH_TTY" ]' {
    set-option -g prefix  C-a
    bind C-a send-prefix
} {
    set-option -g prefix C-s
    bind C-s send-prefix
}

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

set -s set-clipboard on

# unbind -T copy-mode-vi Enter
bind -T copy-mode-vi 'v' send-keys -X begin-selection
bind -T copy-mode-vi Enter send-keys -X copy-selection
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection

#
############################
##  Appearance
############################

%if #{==:#{SSH_TTY},}
    icon=
    maybe_host=""
%else
    icon=󰒍
    maybe_host="#H"
%endif

# disable visual and audio bells
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g monitor-activity off
set -g bell-action none

# statusbar
set -g status-position top

set -g status-left "#[fg=color249,bold]${icon} #S #[nobold]| "
set -g status-left-length 50

set -g status-right "${maybe_host} #[fg=#636da6,bg=#1e2030] %Y/%m/%d #[fg=color233,bg=color8] %H:%M "
set -g status-right-length 50

setw -g window-status-current-format "#[fg=#1e2030,bg=#ffdf77,bold] #I:#[fg=#1e2030,bg=#ffdf77,bold]#W#{?window_zoomed_flag,*Z,} "
setw -g window-status-format "#[fg=#aeb4d1,bg=#1e2030]  #I:#[fg=#aeb4d1,bg=#1e2030]#W#{?window_zoomed_flag,*Z,} "

# vim: set ft=tmux tw=0:
