CompileFlags:
  Add:
    - -ferror-limit=0
    - -Wall
    - -Werror
    - -Wextra
Completion:
  AllScopes: true

---

If:
  PathMatch: .*/linux/tools/usb/usbip/.*

CompileFlags:
  Add:
    - -xc
    - -I../libsrc
  Remove:
    - -xc++
