[[manager.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/dotfiles"
desc = "Goto ~/dotfiles"

[[manager.prepend_keymap]]
on = "<C-p>"
run = "paste"
desc = "Paste (not smart)"

[[manager.prepend_keymap]]
on = "p"
run = "paste --smart"
desc = "Paste (smart)"

# preview with mac quicklook
# [[manager.prepend_keymap]]
# on = "<C-p>"
# run = 'shell -- qlmanage -p "$@"'

# plugins:

[[manager.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on = ["c", "f"]
run = "plugin flatten"
desc = "Flatten selected dirs"

[[manager.prepend_keymap]]
on = ["c", "e"]
run = "plugin select-empty"
desc = "Select empty dirs"

[[manager.prepend_keymap]]
on = ["d", "u"]
run = "plugin restore"
desc = "Restore last deleted files/folders"
